### ISSUE TITLE
Iris crashes on start-up (cannot import Crystal from skued)

### ISSUE THREAD

**Issue by furii** [LaurentRDC/iris-ued#14]
Iris, skued and crystals was installed with pip3 (on "Linux Mint 19.1 Tessa") 
pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
python3 --version
Python 3.6.7

Command line error:

```
Traceback (most recent call last):
  File "/home/krecinic/.local/bin/iris", line 7, in <module>
    from iris.gui import run
  File "/home/krecinic/.local/lib/python3.6/site-packages/iris/gui/__init__.py", line 17, in <module>
    from .gui import Iris, IMAGE_FOLDER
  File "/home/krecinic/.local/lib/python3.6/site-packages/iris/gui/gui.py", line 18, in <module>
    from .calibrate_q_dialog import QCalibratorDialog
  File "/home/krecinic/.local/lib/python3.6/site-packages/iris/gui/calibrate_q_dialog.py", line 9, in <module>
    from skued import Crystal, powder_calq
ImportError: cannot import name 'Crystal'
```

**Comment by LaurentRDC** [comment]
Hello!

I am sorry for this inconvenience. This error will occur if your version of scikit-ued is above 1. The newer 2.0.0 release introduced a new dependency, crystals. Next version of iris-ued will support scikit-ued-2.0.0.

You should downgrade your scikit-ued version to 1.0.1.1:

```bash
python3 -m pip install scikit-ued==1.0.1.1
```

P.S. official support for Linux is coming in the next version as well (iris-ued-5.1.4). You might encounter problems related to multicore operations.

**Comment by furii** [comment]
Hello Laurant, 

Downgrading skued unfortunately does not seem to work. For one, pip still seems to install scikit-ued 2.0.0, and second, I now get a PyQt5 error on trying to start iris instead. Any clue what is going on?

`k@e:~$ pip3 install scikit-ued==1.0.1.1
Collecting scikit-ued==1.0.1.1
  Downloading https://files.pythonhosted.org/packages/6e/0a/bdff500480728ccba774b7baf9c2cdb72c559bb4ce558dbab4dbd7a6b44a/scikit_ued-1.0.1.1-py3-none-any.whl (285kB)
    100% |████████████████████████████████| 286kB 3.1MB/s 
Collecting numpy>=1.12 (from scikit-ued==1.0.1.1)
  Downloading https://files.pythonhosted.org/packages/75/92/57179ed45307ec6179e344231c47da7f3f3da9e2eee5c8ab506bd279ce4e/numpy-1.17.1-cp36-cp36m-manylinux1_x86_64.whl (20.4MB)
    100% |████████████████████████████████| 20.4MB 87kB/s 
Collecting pywavelets>=0.5.2 (from scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/4e/cd/528dba0b474b08f6f9a3a5e1b4bb23d8e33ed5d9f0e321cc967c2607df05/PyWavelets-1.0.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=1.0.0 (from scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/29/50/a552a5aff252ae915f522e44642bb49a7b7b31677f9580cfd11bcc869976/scipy-1.3.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting scikit-image>=0.13 (from scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/d4/ab/674e168bf7d0bc597218b3bec858d02c23fbac9ec1fec9cad878c6cee95f/scikit_image-0.15.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting spglib>=1.10 (from scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/db/5c/332b34cffe7ed7a314c522a3871bfc64a8aad1b873047cae711228392976/spglib-1.14.1.post0-cp36-cp36m-manylinux1_x86_64.whl
Collecting npstreams>=1.5.2 (from scikit-ued==1.0.1.1)
  Downloading https://files.pythonhosted.org/packages/a4/af/f979021f6a9a8439aa936ba75c822efa864b591c34edc6f64714d695192d/npstreams-1.6.1-py3-none-any.whl
Collecting tifffile>=0.13 (from scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/ca/96/2fcac22c806145b34e682e03874b490ae09bc3e48013a0c77e590cd6be29/tifffile-2019.7.26-py2.py3-none-any.whl
Collecting pycifrw>=4 (from scikit-ued==1.0.1.1)
Collecting networkx>=2.0 (from scikit-image>=0.13->scikit-ued==1.0.1.1)
Collecting imageio>=2.0.1 (from scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/af/0a/943c965d372dae0b1f1482677d29030ab834351a61a9a632fd62f27f1523/imageio-2.5.0-py3-none-any.whl
Collecting pillow>=4.3.0 (from scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/14/41/db6dec65ddbc176a59b89485e8cc136a433ed9c6397b6bfe2cd38412051e/Pillow-6.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting matplotlib!=3.0.0,>=2.0.0 (from scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/57/4f/dd381ecf6c6ab9bcdaa8ea912e866dedc6e696756156d8ecc087e20817e2/matplotlib-3.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cython>=0.28 (from npstreams>=1.5.2->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/45/f2/a7101b3457561e57f5abcd6f5ac13190054fecd7370f58f36fe2d6574742/Cython-0.29.13-cp36-cp36m-manylinux1_x86_64.whl
Collecting decorator>=4.3.0 (from networkx>=2.0->scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/f8/a1/5742b56282449b1c0968197f63eae486eca2c35dcd334bab75ad524e0de1/kiwisolver-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting python-dateutil>=2.1 (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting setuptools (from kiwisolver>=1.0.1->matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.13->scikit-ued==1.0.1.1)
  Downloading https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl (576kB)
    100% |████████████████████████████████| 583kB 3.1MB/s 
Collecting six>=1.5 (from python-dateutil>=2.1->matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.13->scikit-ued==1.0.1.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: numpy, pywavelets, scipy, decorator, networkx, pillow, imageio, setuptools, kiwisolver, six, python-dateutil, pyparsing, cycler, matplotlib, scikit-image, spglib, cython, npstreams, tifffile, pycifrw, scikit-ued
Successfully installed cycler-0.10.0 cython-0.29.13 decorator-4.4.0 imageio-2.5.0 kiwisolver-1.1.0 matplotlib-3.1.1 networkx-2.3 npstreams-1.6.1 numpy-1.17.1 pillow-6.1.0 pycifrw-4.4.1 pyparsing-2.4.2 python-dateutil-2.8.0 pywavelets-1.0.3 scikit-image-0.15.0 scikit-ued-2.0.0 scipy-1.3.1 setuptools-41.2.0 six-1.12.0 spglib-1.14.1.post0 tifffile-2019.7.26
k@e:~$ which iris
/home/krecinic/.local/bin/iris
k@e:~$ iris 
Traceback (most recent call last):
  File "/home/krecinic/.local/bin/iris", line 11, in <module>
    sys.exit(run())
  File "/home/krecinic/.local/lib/python3.6/site-packages/iris/gui/__init__.py", line 70, in run
    app = QtGui.QApplication(sys.argv)
AttributeError: module 'PyQt5.QtGui' has no attribute 'QApplication'
krecinic@endymion:~$ pip3 show pyqt5
Name: PyQt5
Version: 5.13.0
Summary: Python bindings for the Qt cross platform UI and application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: /home/krecinic/.local/lib/python3.6/site-packages
Requires: PyQt5-sip
`

**Comment by LaurentRDC** [comment]
I see from the top lines that scikit-ued 1.0.1.1 is correctly installed. It is possible that both versions (1.0.1.1 and 2.0.0) are installed simultaneously; in this case, I'm guessing you will want to uninstall scikit-ued-2.0.0.

As for the PyQt5 problem, I have no idea. My experience is mostly on Windows. I believe that this problem can arise if a dependency of PyQt5 (sip) is not installed correctly.

If you have access to the package manager `conda`, I would recommend you use it instead. You can then create a separate environment for iris.

**Comment by LaurentRDC** [comment]
Closed for lack of activity. I'm happy to re-open it if I can help further.
