### ISSUE TITLE
Issues with loading dataset

### ISSUE THREAD

**Issue by SK001-E** [LaurentRDC/iris-ued#26]
#### Version / Platform Info
- iris-ued version: 5.3.4
- Happens in latest version? (Yes/No): Yes 
- Known Operating System(s) affected__: Windows 10 & 11
  - [x] Windows
  - [ ] Linux
  - [ ] Mac OS
- Installation method: conda install and git clone
  - [ ] Windows installer
  - [ ] pip
  - [x] conda

#### Expected Behavior

I have issues with loading dataset (hdf5). I have successfully used iris-ued before and experienced issues only recently. When I load dataset using gui it gives following error:

C:\Users\sumit\Documents\iris-ued\iris\gui\controller.py:38: UserWarning: Traceback (most recent call last):
  File "C:\Users\sumit\Documents\iris-ued\iris\gui\controller.py", line 32, in aware_func
    return func(self, *args, **kwargs)
  File "C:\Users\sumit\Documents\iris-ued\iris\gui\controller.py", line 611, in load_dataset
    self.dataset = cls(path, mode="r+")
  File "C:\Users\sumit\Documents\iris-ued\iris\dataset.py", line 130, in __init__
    self._migration_checks()
  File "C:\Users\sumit\Documents\iris-ued\iris\dataset.py", line 140, in _migration_checks
    self._autocenter()
  File "C:\Users\sumit\Documents\iris-ued\iris\dataset.py", line 53, in newf
    return f(self, *args, **kwargs)
  File "C:\Users\sumit\Documents\iris-ued\iris\dataset.py", line 870, in _autocenter
    raise ValueError(
ValueError: There is not enough data to determine a center; all valid pixels have zero intensity.

This error was present for dataset which were being loaded without any error.

**Comment by LaurentRDC** [comment]
Hello,

iris has a migration routine which will update older datasets with extra metadata. In this case, during migration, iris is trying to determine the center of the diffraction patterns but failing:

> ValueError: There is not enough data to determine a center; all valid pixels have zero intensity.

This shouldn't happen; let me create a fix which should determine the center to be some reasonable default value instead of throwing an exception

**Comment by LaurentRDC** [comment]
A fix has been made in a new version (5.3.5) and the automatic release process is ongoing. 

In about ~24h, you'll be able to upgrade iris and open your dataset once again. Please come back and let me know whether your problem has been fixed or not

**Comment by LaurentRDC** [comment]
I'm going to close this for now, as the issue should be fixed. Feel free to re-open if it is not the case.
