### ISSUE TITLE
Request: Cite iris on pyqtgraph poster board session at SciPy 2023

### ISSUE THREAD

**Issue by j9ac9k** [LaurentRDC/iris-ued#27]
Hello iris maintainers,

PyQtGraph maintainer here, sorry for the noise on your issue tracker, I didn't know how else to reach out to you all.

We would like permission to use a screenshot of iris on our poster board session at SciPy this coming week.  Yes, it's next week, yes this is last minute, yes, we did not plan far enough in advance 😅 

We would of course site your project with the screenshot, but I wanted to get your permission before doing so.  If you'd like to continue this discussion, not on github, my contact information is in my github user profile, feel free to contact me by whatever means is easiest. 

The screenshot in your README is 🔥 🔥 🔥

**Comment by LaurentRDC** [comment]
Hi Ogi,

I would be thrilled if you used the screenshot from the README in any material.

Would you be able to post a link to the poster once it has been presented?

**Comment by j9ac9k** [comment]
> Hi Ogi,
> 
> 
> 
> I would be thrilled if you used the screenshot from the README in any material.
> 
> 
> 
> Would you be able to post a link to the poster once it has been presented? 

We would be happy to provide a link to the finished product.

I'll try and recreate the screenshots but if you have an "easy" way of taking a screenshot in light mode and/or with a high resolution, that would be very helpful!

Does iris expose PyQtGraph's SVG exporter?

**Comment by LaurentRDC** [comment]
Unfortunately there's no way I or anyone can re-create this screenshot, as the data required is out of reach in cold storage at the moment. There's no way I could get the data out in the next week.

The original can be downloaded below (until Sept 1st, 2023), although it might be the exact same file as is visible on GitHub:

https://1drv.ms/i/s!Apo2osBnhhf4o9My-qZ57_P7sBaLhA?e=waNjgZ

**Comment by j9ac9k** [comment]
It certainly doesn't need to be a perfect match. As iris seems to do tasks _well_ outside my field, I'll attempt to render the data in a similar fashion and grab relevant screen shots.

I'll post back if I'm having issues.  Thanks you all for the quick replies 🙏🙏🙏

**Comment by j9ac9k** [comment]
Unrelated to this issue, but I hope PyQtGraph has worked well for your project. 

If there are issues that are highly impacting you, or feature requests that would unlock significant functionality please don't hesitate to reach out to us.  We try and tailor our efforts towards issues that would make the most difference to our users.

**Comment by LaurentRDC** [comment]
Thanks Ogi. We've been completely satisfied with the speed and customizability of PyQtGraph, and now the software is stable and feature-complete

**Comment by j9ac9k** [comment]
I got the screenshot you linked, thanks; I also downloaded some of your test datasets (the test data on the README section no longer exists btw) and loaded it up w/o issue, I have no idea what I'm looking at, but you made it gorgeous 😆 

Also, you left the exporters accessible so I am able to export graphs as SVGs.  

Here is our submission to SciPy (paper, not poster, poster we're still working on) in case you're curious; I'll come back and update you with a link to the poster. 

https://github.com/scipy-conference/scipy_proceedings/pull/828

**Comment by j9ac9k** [comment]
Here's our poster! https://drive.google.com/file/d/1-Q6Akm5nbIbu-3KeJyPR2PKFUr1_LyOo/view?usp=sharing

Thank you for allowing us to use iris in our collage!
